"""empty message

Revision ID: c56158d712d5
Revises: c9a85967bd42
Create Date: 2024-06-27 13:34:01.614092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56158d712d5'
down_revision = 'c9a85967bd42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crime',
    sa.Column('crime_id', sa.Integer(), nullable=False),
    sa.Column('crime_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('crime_id')
    )
    op.create_table('prison',
    sa.Column('prison_id', sa.Integer(), nullable=False),
    sa.Column('prison_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('prison_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('prisoner',
    sa.Column('prisoner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other'), nullable=False),
    sa.Column('crime_id', sa.Integer(), nullable=False),
    sa.Column('sentence_years', sa.Integer(), nullable=False),
    sa.Column('prison_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crime_id'], ['crime.crime_id'], ),
    sa.ForeignKeyConstraint(['prison_id'], ['prison.prison_id'], ),
    sa.PrimaryKeyConstraint('prisoner_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prisoner')
    op.drop_table('user')
    op.drop_table('prison')
    op.drop_table('crime')
    # ### end Alembic commands ###
